# Generated by Django 5.2.8 on 2025-11-09 19:43

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(help_text="Введите e-mail", max_length=254, verbose_name="E-mail")),
                ("country", django_countries.fields.CountryField(default="ru", max_length=2)),
                ("city", models.CharField(help_text="Введите город", max_length=150, verbose_name="Город")),
                ("street", models.CharField(help_text="Введите улицу", max_length=150, verbose_name="Улица")),
                ("house", models.CharField(help_text="Введите номер дома", max_length=10, verbose_name="Номер дома")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Введите название продукта", max_length=150, verbose_name="Название"),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        help_text="Введите модель продукта",
                        max_length=200,
                        null=True,
                        verbose_name="Модель",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True,
                        help_text="Введите дату выхода на рынок",
                        null=True,
                        verbose_name="Дата выхода на рынок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="NetworkNode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Введите название звена сети", max_length=150, verbose_name="Название"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("factory", "Завод"),
                            ("retail", "Розничная сеть"),
                            ("entrepreneur", "Индивидуальный предприниматель"),
                        ],
                        help_text="Выберите тип звена сети",
                        max_length=15,
                        verbose_name="Тип звена",
                    ),
                ),
                ("level", models.PositiveIntegerField(editable=False, verbose_name="Уровень в иерархии")),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Введите задолженность перед поставщиком в рублях",
                        max_digits=12,
                        verbose_name="Задолженность перед поставщиком",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Время создания")),
                (
                    "contact",
                    models.ManyToManyField(
                        help_text="Выберите контакты для этого звена сети",
                        to="network.contact",
                        verbose_name="Контакты",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите поставщика оборудования",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child",
                        to="network.networknode",
                        verbose_name="Поставщик",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        help_text="Выберите продукты, которые реализует это звено",
                        to="network.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Звено сети",
                "verbose_name_plural": "Звенья сети",
            },
        ),
    ]
