# Generated by Django 5.2.8 on 2025-11-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "контакт", "verbose_name_plural": "Контакты"},
        ),
        migrations.AlterModelOptions(
            name="networknode",
            options={"verbose_name": "звено сети", "verbose_name_plural": "Звенья сети"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.RenameField(
            model_name="networknode",
            old_name="contact",
            new_name="contacts",
        ),
        migrations.AlterField(
            model_name="networknode",
            name="type",
            field=models.CharField(
                choices=[("factory", "Завод"), ("retail", "Розничная сеть"), ("entrepreneur", "ИП")],
                help_text="Выберите тип звена сети",
                max_length=15,
                verbose_name="Тип звена",
            ),
        ),
    ]
